//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Act_concedida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Act_concedida()
        {
            this.Horario_Act_Con = new HashSet<Horario_Act_Con>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_tipo { get; set; }
        public int id_equipo { get; set; }
        public int id_act_demandadas { get; set; }
        public int id_usuario { get; set; }
        public int id_espacio { get; set; }
    
        public virtual Act_demandadas Act_demandadas { get; set; }
        public virtual Equipo Equipo { get; set; }
        public virtual Espacio Espacio { get; set; }
        public virtual Tipo_Actitivades Tipo_Actitivades { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario_Act_Con> Horario_Act_Con { get; set; }
    }
}
