//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoBDJordiEntities : DbContext
    {
        public ProyectoBDJordiEntities()
            : base("name=ProyectoBDJordiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Act_concedida> Act_concedida { get; set; }
        public virtual DbSet<Act_demandadas> Act_demandadas { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Categoria_edad> Categoria_edad { get; set; }
        public virtual DbSet<Categoria_Edat> Categoria_Edat { get; set; }
        public virtual DbSet<Competicion> Competicion { get; set; }
        public virtual DbSet<Deportes> Deportes { get; set; }
        public virtual DbSet<Dias_Semana> Dias_Semana { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<Equipo> Equipo { get; set; }
        public virtual DbSet<Espacio> Espacio { get; set; }
        public virtual DbSet<Horario_Act_Con> Horario_Act_Con { get; set; }
        public virtual DbSet<Horario_Act_Dem> Horario_Act_Dem { get; set; }
        public virtual DbSet<Instalacion> Instalacion { get; set; }
        public virtual DbSet<Instalacion_Horario> Instalacion_Horario { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<Telefonos> Telefonos { get; set; }
        public virtual DbSet<Tipo_Actitivades> Tipo_Actitivades { get; set; }
        public virtual DbSet<Tipo_gestion> Tipo_gestion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
