//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Act_concedida = new HashSet<Act_concedida>();
            this.Act_demandadas = new HashSet<Act_demandadas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_sport { get; set; }
        public Nullable<int> id_competicion { get; set; }
        public Nullable<int> id_categoria_edad { get; set; }
        public Nullable<int> id_nivel { get; set; }
        public Nullable<int> id_sexo { get; set; }
        public Nullable<int> id_entidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Act_concedida> Act_concedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Act_demandadas> Act_demandadas { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Categoria_edad Categoria_edad { get; set; }
        public virtual Competicion Competicion { get; set; }
        public virtual Deportes Deportes { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual Entidad Entidad { get; set; }
    }
}
