//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.Act_concedida = new HashSet<Act_concedida>();
            this.Act_demandadas = new HashSet<Act_demandadas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_sport { get; set; }
        public int id_competicion { get; set; }
        public int id_categoria_edad { get; set; }
        public int id_nivel { get; set; }
        public int id_sexo { get; set; }
        public int id_entidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Act_concedida> Act_concedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Act_demandadas> Act_demandadas { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Categoria_edad Categoria_edad { get; set; }
        public virtual Competicion Competicion { get; set; }
        public virtual Deportes Deportes { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Sexo Sexo { get; set; }
    }
}
