//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPLETE_FLAT_UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int id { get; set; }
        public int telefono { get; set; }
        public string razon { get; set; }
        public int id_entidad { get; set; }
    
        public virtual Entidad Entidad { get; set; }
    }
}
